/**
 * EdgeFlow Framework v1.0 — SafeNest Integration Example
 * ========================================================
 * Full SafeNest smart home safety system with EdgeFlow ML
 * replacing the original hardcoded gas threshold rule.
 *
 * ORIGINAL SAFENEST HARDWARE:
 *   MQ-2 gas sensor  → GPIO 34 (ADC, 0–4095)
 *   PIR sensor 1     → GPIO 27 (digital, 0/1)
 *   PIR sensor 2     → GPIO 26 (digital, 0/1)
 *   Relay 1          → GPIO 13
 *   Relay 2          → GPIO 12
 *   Relay 3          → GPIO 33
 *   Buzzer           → GPIO 14
 *   Green LED        → GPIO 18
 *   Red LED          → GPIO 19
 *
 * HOW TO USE:
 *   1. edgeflow generate-data --domain safenest --samples 500
 *   2. edgeflow train --data safenest_data.csv --model decision_tree --target esp32 --domain safenest
 *   3. edgeflow export --output safenest_model --format header
 *   4. Copy safenest_model.h into this sketch folder
 *   5. Upload and open Serial Monitor at 115200 baud
 *
 * LABEL MAP (from generated header):
 *   0 = DANGER   (EdgeFlow detected dangerous gas levels)
 *   1 = SAFE     (normal air quality)
 *
 * NOTE: Check result.label == 0 for DANGER, not 1.
 *       The label encoding is determined by the Python trainer's
 *       LabelEncoder which sorts labels alphabetically:
 *       DANGER (0) < SAFE (1)
 */

// ============================================================
// IMPORTANT: Include model header BEFORE EdgeFlow.h
// The model header defines EDGEFLOW_MODEL_TYPE which selects
// the correct inference engine at compile time.
// ============================================================
#include "safenest_model.h"   // Auto-generated by EdgeFlow Python toolkit
#include <EdgeFlow.h>

// ============================================================
// PIN DEFINITIONS — Original SafeNest hardware mapping
// ============================================================
#define MQ2_PIN     34    // MQ-2 gas sensor (ADC input)
#define PIR1_PIN    27    // PIR motion sensor 1
#define PIR2_PIN    26    // PIR motion sensor 2
#define RELAY1      13    // Relay 1 (e.g. gas valve cutoff)
#define RELAY2      12    // Relay 2
#define RELAY3      33    // Relay 3
#define BUZZER_PIN  14    // Buzzer for alert
#define GREEN_LED   18    // Green LED (SAFE indicator)
#define RED_LED     19    // Red LED (DANGER indicator)

// ============================================================
// GLOBAL STATE — same as original SafeNest
// ============================================================
int  gasValue  = 0;
bool motion1   = false;
bool motion2   = false;
bool gasAlert  = false;

// ============================================================
// FORWARD DECLARATIONS
// ============================================================
void readSensors();
void gasSafetySystem();
void updateRelays();
void updateIndicators();
void printStatus();

// ============================================================
// setup()
// ============================================================
void setup() {
    Serial.begin(115200);
    delay(500);

    // Pin modes — identical to original SafeNest
    pinMode(MQ2_PIN,    INPUT);
    pinMode(PIR1_PIN,   INPUT);
    pinMode(PIR2_PIN,   INPUT);
    pinMode(RELAY1,     OUTPUT);
    pinMode(RELAY2,     OUTPUT);
    pinMode(RELAY3,     OUTPUT);
    pinMode(BUZZER_PIN, OUTPUT);
    pinMode(GREEN_LED,  OUTPUT);
    pinMode(RED_LED,    OUTPUT);

    // Safe default state — all relays off, green LED on
    digitalWrite(RELAY1, LOW);
    digitalWrite(RELAY2, LOW);
    digitalWrite(RELAY3, LOW);
    digitalWrite(BUZZER_PIN, LOW);
    digitalWrite(GREEN_LED, HIGH);
    digitalWrite(RED_LED,   LOW);

    // Initialize EdgeFlow — prints version banner to Serial
    EdgeFlow.begin();
    EdgeFlow.printModelInfo();

    Serial.println(F("SafeNest + EdgeFlow ready."));
    Serial.println(F("Monitoring gas and motion sensors..."));
    Serial.println();
}

// ============================================================
// loop()
// ============================================================
void loop() {
    readSensors();       // 1. Read hardware sensors
    gasSafetySystem();   // 2. ML inference — sets gasAlert
    updateRelays();      // 3. Drive relays based on alert state
    updateIndicators();  // 4. Update LEDs and buzzer
    printStatus();       // 5. Serial log for monitoring
    delay(500);          // 6. Sample at 2 Hz
}

// ============================================================
// readSensors()
// Read MQ-2 ADC and both PIR sensors into global variables.
// Identical to original SafeNest sensor read logic.
// ============================================================
void readSensors() {
    gasValue = analogRead(MQ2_PIN);      // 0–4095 on ESP32 ADC
    motion1  = digitalRead(PIR1_PIN);   // 0 or 1
    motion2  = digitalRead(PIR2_PIN);   // 0 or 1
}

// ============================================================
// gasSafetySystem()
//
// ---- BEFORE EdgeFlow (original SafeNest hardcoded rule): ----
//   if (gasValue > 2500) {
//       gasAlert = true;
//   } else {
//       gasAlert = false;
//   }
//
// ---- AFTER EdgeFlow (ML inference): ----
//   Build input array → predict() → check result.label
//
// LABEL MAP: 0 = DANGER, 1 = SAFE
// So: result.label == 0 means DANGER (trigger alert)
//     result.label == 1 means SAFE   (clear alert)
// ============================================================
void gasSafetySystem() {
    // Build the input feature array in the same order as training CSV:
    //   Feature 0: mq2_raw    (ADC reading 0–4095)
    //   Feature 1: pir_state  (1 if any motion detected, 0 otherwise)
    float input[EDGEFLOW_N_FEATURES] = {
        (float)gasValue,
        (float)(motion1 || motion2)   // combine both PIRs into single boolean feature
    };

    // Run ML inference — auto-selects DT / LR / NB at compile time
    EdgeFlowResult result = EdgeFlow.predict(input, EDGEFLOW_N_FEATURES);

    if (!result.success) {
        // Prediction failed (no model header included) — fail safe
        Serial.println(F("[EdgeFlow] ERROR: prediction failed. Defaulting to SAFE."));
        gasAlert = false;
        return;
    }

    // LABEL MAP: 0 = DANGER, 1 = SAFE
    if (result.label == 0) {
        // EdgeFlow detected DANGER
        gasAlert = true;

        Serial.print(F("[EdgeFlow] DANGER detected"));
        Serial.print(F(" | Confidence: ")); Serial.print(result.confidence, 1); Serial.print(F("%"));
        Serial.print(F(" | Latency: "));    Serial.print(result.latency_ms, 3);  Serial.print(F("ms"));
        Serial.print(F(" | Memory: "));     Serial.print(result.memory_used_kb, 2); Serial.println(F("KB"));

    } else {
        // result.label == 1 → SAFE
        gasAlert = false;
    }
}

// ============================================================
// updateRelays()
// Drive relay outputs based on gasAlert state.
// Original SafeNest relay logic preserved exactly.
// ============================================================
void updateRelays() {
    if (gasAlert) {
        // DANGER: energize all safety relays (cut gas valve, ventilation, etc.)
        digitalWrite(RELAY1, HIGH);
        digitalWrite(RELAY2, HIGH);
        digitalWrite(RELAY3, HIGH);
    } else {
        // SAFE: de-energize all relays (normal operation)
        digitalWrite(RELAY1, LOW);
        digitalWrite(RELAY2, LOW);
        digitalWrite(RELAY3, LOW);
    }
}

// ============================================================
// updateIndicators()
// LED and buzzer state mirrors gasAlert.
// Original SafeNest indicator logic preserved exactly.
// ============================================================
void updateIndicators() {
    if (gasAlert) {
        // DANGER: red LED on, green LED off, buzzer on
        digitalWrite(RED_LED,    HIGH);
        digitalWrite(GREEN_LED,  LOW);
        digitalWrite(BUZZER_PIN, HIGH);
    } else {
        // SAFE: green LED on, red LED off, buzzer off
        digitalWrite(GREEN_LED,  HIGH);
        digitalWrite(RED_LED,    LOW);
        digitalWrite(BUZZER_PIN, LOW);
    }
}

// ============================================================
// printStatus()
// Brief periodic log to Serial Monitor.
// ============================================================
void printStatus() {
    Serial.print(F("GAS: ")); Serial.print(gasValue);
    Serial.print(F("  PIR1: ")); Serial.print(motion1 ? "YES" : "no ");
    Serial.print(F("  PIR2: ")); Serial.print(motion2 ? "YES" : "no ");
    Serial.print(F("  ALERT: ")); Serial.println(gasAlert ? "DANGER" : "safe  ");
}
